### ISSUE TITLE
Other chess bots other than Stockfish

### ISSUE THREAD

**Issue by Baconartist** [PanagiotisIatrou/chess-auto-bot#39] opened 2023-04-23 00:09 UTC
Hi! I recall opening an issue about this because I thought it was already implemented, and was confused when it didn't move despite being connected.

I would love to see any engine being used in your program. I'm no developer, but it would really cool for me to be able to use the zappa engine, which is a bot that likes to make moves that seem like blunders but aren't. There are a lot of bots I would love to try out!

**Comment by PanagiotisIatrou** [comment] 2023-04-23 08:20
Hello @Baconartist. You opened the same issue some time ago (https://github.com/PanagiotisIatrou/chess-auto-bot/issues/35). I closed this because it is a duplicate of https://github.com/PanagiotisIatrou/chess-auto-bot/issues/21 and that's the reason I am going to close this issue too.

**Closed by PanagiotisIatrou** 2023-04-23 08:20 UTC
