### ISSUE TITLE
Cannot use any other engines other than Stockfish 15.1

### ISSUE THREAD

**Issue by Baconartist** [PanagiotisIatrou/chess-auto-bot#35] opened 2023-04-12 02:07 UTC
I wish to use the zappa bot. I put in the executable in the path, yet it will say "starting" indefinitely. I have loaded this same executable inside arena, and it works.

**Comment by PanagiotisIatrou** [comment] 2023-04-16 13:30
Hello, currently there is no support for engines other than Stockfish. I am closing this issue as it is a duplicate of https://github.com/PanagiotisIatrou/chess-auto-bot/issues/21

**Closed by PanagiotisIatrou** 2023-04-16 13:30 UTC
