### ISSUE TITLE
Stockfish dev build

### ISSUE THREAD

**Issue by Zeptanz** [PanagiotisIatrou/chess-auto-bot#27] opened 2023-02-25 15:47 UTC
STOCKFISH DEV BUILD doesn’t work

**Comment by PanagiotisIatrou** [comment] 2023-02-25 16:47
Hello @Zeptanz. This issue is a duplicate of https://github.com/PanagiotisIatrou/chess-auto-bot/issues/6. Please refer to it to solve it.

**Closed by PanagiotisIatrou** 2023-02-25 16:47 UTC
